# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 400)
        MainWindow.setMinimumSize(QtCore.QSize(1150, 400))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabRecord = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tabRecord.sizePolicy().hasHeightForWidth())
        self.tabRecord.setSizePolicy(sizePolicy)
        self.tabRecord.setObjectName("tabRecord")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabRecord)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 9, 1131, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleTab1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleTab1.sizePolicy().hasHeightForWidth())
        self.titleTab1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.titleTab1.setFont(font)
        self.titleTab1.setAlignment(QtCore.Qt.AlignCenter)
        self.titleTab1.setObjectName("titleTab1")
        self.verticalLayout.addWidget(self.titleTab1)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setSpacing(6)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.choix1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choix1.setFont(font)
        self.choix1.setAutoDefault(False)
        self.choix1.setDefault(False)
        self.choix1.setFlat(False)
        self.choix1.setObjectName("choix1")
        self.horizontalLayout1.addWidget(self.choix1)
        self.choix2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choix2.setFont(font)
        self.choix2.setObjectName("choix2")
        self.horizontalLayout1.addWidget(self.choix2)
        self.choix3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choix3.setFont(font)
        self.choix3.setObjectName("choix3")
        self.horizontalLayout1.addWidget(self.choix3)
        self.verticalLayout.addLayout(self.horizontalLayout1)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setSpacing(6)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.choix4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choix4.setFont(font)
        self.choix4.setObjectName("choix4")
        self.horizontalLayout2.addWidget(self.choix4)
        self.choix5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choix5.setFont(font)
        self.choix5.setObjectName("choix5")
        self.horizontalLayout2.addWidget(self.choix5)
        self.choix6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choix6.setFont(font)
        self.choix6.setObjectName("choix6")
        self.horizontalLayout2.addWidget(self.choix6)
        self.verticalLayout.addLayout(self.horizontalLayout2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.resultLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")
        self.verticalLayout.addWidget(self.resultLabel)
        self.tabWidget.addTab(self.tabRecord, "")
        self.tabData = QtWidgets.QWidget()
        self.tabData.setObjectName("tabData")
        self.gridLayout = QtWidgets.QGridLayout(self.tabData)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.titleTab2 = QtWidgets.QLabel(self.tabData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleTab2.sizePolicy().hasHeightForWidth())
        self.titleTab2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.titleTab2.setFont(font)
        self.titleTab2.setAlignment(QtCore.Qt.AlignCenter)
        self.titleTab2.setObjectName("titleTab2")
        self.verticalLayout_4.addWidget(self.titleTab2)
        self.allDataTableView = QtWidgets.QTableView(self.tabData)
        self.allDataTableView.setObjectName("allDataTableView")
        self.verticalLayout_4.addWidget(self.allDataTableView)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabData, "")
        self.tabAnalysis = QtWidgets.QWidget()
        self.tabAnalysis.setObjectName("tabAnalysis")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabAnalysis)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tabAnalysis)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -429, 1094, 743))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleTab3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.titleTab3.setFont(font)
        self.titleTab3.setAlignment(QtCore.Qt.AlignCenter)
        self.titleTab3.setObjectName("titleTab3")
        self.verticalLayout_2.addWidget(self.titleTab3)
        self.label_analyse1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_analyse1.setObjectName("label_analyse1")
        self.verticalLayout_2.addWidget(self.label_analyse1)
        self.tableView_1 = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tableView_1.setObjectName("tableView_1")
        self.verticalLayout_2.addWidget(self.tableView_1)
        self.label_analyse2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_analyse2.setObjectName("label_analyse2")
        self.verticalLayout_2.addWidget(self.label_analyse2)
        self.tableView_2 = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_2.addWidget(self.tableView_2)
        self.label_analyse3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_analyse3.setObjectName("label_analyse3")
        self.verticalLayout_2.addWidget(self.label_analyse3)
        self.tableView_3 = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout_2.addWidget(self.tableView_3)
        self.label_analyse4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_analyse4.setObjectName("label_analyse4")
        self.verticalLayout_2.addWidget(self.label_analyse4)
        self.tableView_4 = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tableView_4.setObjectName("tableView_4")
        self.verticalLayout_2.addWidget(self.tableView_4)
        self.label_analyse5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_analyse5.setObjectName("label_analyse5")
        self.verticalLayout_2.addWidget(self.label_analyse5)
        self.tableView_5 = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tableView_5.setObjectName("tableView_5")
        self.verticalLayout_2.addWidget(self.tableView_5)
        self.label_analyse6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_analyse6.setObjectName("label_analyse6")
        self.verticalLayout_2.addWidget(self.label_analyse6)
        self.tableView_6 = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tableView_6.setObjectName("tableView_6")
        self.verticalLayout_2.addWidget(self.tableView_6)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabAnalysis, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sondage Abc"))
        self.titleTab1.setText(_translate("MainWindow", "Quel était le motif de la visite?"))
        self.choix1.setText(_translate("MainWindow", "Choix 1"))
        self.choix2.setText(_translate("MainWindow", "Choix 2"))
        self.choix3.setText(_translate("MainWindow", "Choix 3"))
        self.choix4.setText(_translate("MainWindow", "Choix 4"))
        self.choix5.setText(_translate("MainWindow", "Choix 5"))
        self.choix6.setText(_translate("MainWindow", "Choix 6"))
        self.resultLabel.setText(_translate("MainWindow", "Dernière visite enregistrée : Inscription à 10:00"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRecord), _translate("MainWindow", "Visite"))
        self.titleTab2.setText(_translate("MainWindow", "Données collectées"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabData), _translate("MainWindow", "Données"))
        self.titleTab3.setText(_translate("MainWindow", "Analyse des données"))
        self.label_analyse1.setText(_translate("MainWindow", "analyse1"))
        self.label_analyse2.setText(_translate("MainWindow", "analyse2"))
        self.label_analyse3.setText(_translate("MainWindow", "analyse3"))
        self.label_analyse4.setText(_translate("MainWindow", "analyse4"))
        self.label_analyse5.setText(_translate("MainWindow", "analyse5"))
        self.label_analyse6.setText(_translate("MainWindow", "analyse6"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnalysis), _translate("MainWindow", "Analyse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
